language: go

sudo: false

go:
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10"

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test -v -race -cover
  - $GOPATH/bin/goveralls -service=travis-ci
