name: goreleaser

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25

      - name: setup required binaries
        run: |
          curl -O -L "https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64"
          sudo mv cosign-linux-amd64 /usr/local/bin/cosign
          sudo chmod +x /usr/local/bin/cosign

          curl -sSfL https://get.anchore.io/syft | sudo sh -s -- -b /usr/local/bin

      - name: setup assets
        run: |
          go mod tidy

          # Compress manpage
          gzip -c manpages/imgx.1 > manpages/imgx.1.gz

          mkdir -p completions

          go build -o imgx ./cmd/imgx

          ./imgx completions zsh > completions/_imgx
          ./imgx completions bash > completions/imgx.bash
          ./imgx completions fish > completions/imgx.fish

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
